### PR TITLE
Use entrySet() instead of keySet() for iteration

### PR DESCRIPTION
**Pull request by kostis**
It's pointless to create a set of keys of a Java map in situations where
the intent is to do some operation on all entries. It's better to create
the entry set instead and iterate over it directly.

### CODE REVIEW

**Comment by fhowar** [comment]
I would suggest to do PR #30 first as there will be conflicts between the two PRs and we will have to recreate #30 by cherry picking after merging the rattt-dt branch

**Comment by kostis** [comment]
rebased on current `main` and fixed conflict.

**Comment by fhowar** [comment]
Looks good to me.

**Review by fhowar — APPROVED** [review]
as commented: looks good to me.

**Pull request merged**
